name: 'Store GitHub credential'
description: 'This action internally creates a new keychain and stores the GitHub credentials in that keychain.'
inputs:
  username:
    description: 'GitHub username'
    required: true
    default: 'GitHub username'
  password:
    description: 'A personal access token with access to the GitHub repository'
    required: true
    default: ''
  timeout:
    description: 'Specify timeout interval in seconds.'
    required: false
    default: '21600'
  keychain:
    description: 'If you want to use a keychain that has already been created, specify the path to that keychain.'
    required: false
    default: ''
  keychain-password:
    description: 'Keychain password'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "download"
  color: "orange"