name: 'Store GitHub credential'
description: 'This action internally creates a new keychain and stores the GitHub credentials in that keychain.'
inputs:
  username:
    description: 'GitHub username'
    required: true
    default: 'GitHub username'
  password:
    description: 'Password or Personal Access Token (PAT)'
    required: true
    default: 'A personal access token with access to the GitHub repository'
  keychain-password:
    description: 'Keychain password'
    required: false
    default: 'Internally generated keychain passwords'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "download"
  color: "orange"