name: Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Install git-credential-manager-core
        run: |
          brew tap microsoft/git
          brew install --cask git-credential-manager-core

      - name: Install dependencies
        run: npm install && npm install @types/uuid

      - name: Default Loging keychain
        uses: ./
        with:
          github-username: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_USERNAME }}
          github-password: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_PAT }}

      - uses: akiojin/setup-temporary-keychain-github-action@v1.0
        id: setup-temporary-keychain

      - name: Create temporary keychain
        uses: ./
        with:
          github-username: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_USERNAME }}
          github-password: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_PAT }}
          keychain: ${{ steps.setup-temporary-keychain.outputs.keychain }}
          keychain-password: ${{ steps.setup-temporary-keychain.outputs.keychain-password }}